### ISSUE TITLE
Can I, and how, check if rewarded ad is loaded?

### ISSUE THREAD

**Issue by ixzor** [MichaelStott/KivMob#106]
Hi,
I want to check if rewarded ad is loaded, like you can do with interstitial ads (is_interstitial_loaded()) but I don't see it in documentation. Can anybody clear that up for me?
Thanks in advance

**Comment by MichaelStott** [comment]
Apologies for the delayed response. New development for this project has been rather slow.

For anyone trying to check this, it should be possible via one of the reward ad callbacks: http://kivmob.com/kivmob.html#kivmob.RewardedListenerInterface.on_rewarded_video_ad_loaded
