### ISSUE TITLE
Does the kivmob work at the moment?

### ISSUE THREAD

**Issue by Googler43** [MichaelStott/KivMob#108]
I'm trying to build an application with a banner and nothing comes out in any form. Not changing api 27 to 30, not ad banner id. Nothing helps.
In the logs I see only  "request_interstitial() called."  And nothing happens on the screen

**Comment by MichaelStott** [comment]
Looking into it.

**Comment by MichaelStott** [comment]
Seems to be working, are you seeing any additional logs?

**Comment by MichaelStott** [comment]
Closing this for now. There are often issues such as this when running KivMob. Just as note for folks who may also open up issues similar to this, please share your logcat and buildozer.spec file.
