### ISSUE TITLE
Interstitial Ads Not Working

### ISSUE THREAD

**Issue by boyintheroom** [MichaelStott/KivMob#130]
@MichaelStott @nekoprog  Rewarded ads wont work so i switched to Interstitial ads. And now Interstitial Wont work.

***Logs
03-07 20:53:59.100 20123 20123 I python  :  Traceback (most recent call last):
03-07 20:53:59.100 20123 20123 I python  :    File "/home/dheeraj/phenon/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/Phenon/armeabi-v7a/android/runnable.py", line 38, in run
03-07 20:53:59.101 20123 20123 I python  :    File "/home/dheeraj/phenon/.buildozer/android/app/kivmob.py", line 188, in __init__
03-07 20:53:59.102 20123 20123 I python  :  NameError: name 'MobileAds' is not defined
03-07 20:53:59.103 20123 20721 I python  : [INFO   ] [KivMob      ] new_interstitial() called.
03-07 20:53:59.115 20123 20123 I python  :  Traceback (most recent call last):
03-07 20:53:59.115 20123 20123 I python  :    File "/home/dheeraj/phenon/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/Phenon/armeabi-v7a/android/runnable.py", line 38, in run
03-07 20:53:59.116 20123 20123 I python  :    File "/home/dheeraj/phenon/.buildozer/android/app/kivmob.py", line 233, in new_interstitial
03-07 20:53:59.117 20123 20123 I python  :  AttributeError: 'AndroidBridge' object has no attribute '_interstitial'

***

**Comment by mulivham** [comment]
can't read logs, Interstitial ads showing for me after pressing the button multiple time when testing.

i added (android.gradle_dependencies =com.google.firebase:firebase-ads:15.0.0) on my buildozer file

i have problem with banner ads not showing

**Comment by boyintheroom** [comment]
@mulivham hi friend.
You are asking me or you are telling me the soultion?
Can you tell me breifly i didnt understand what are you trying to say my friend.

**Comment by mulivham** [comment]
I'm saying that Interstitial ads worked for me after i add the following line >( android.gradle_dependencies =com.google.firebase:firebase-ads:15.0.0 ) on the buildozer spec file. try it and see if it will work for you but it never show on the banner ads

**Comment by boyintheroom** [comment]
@mulivham i did buildozer android clean and it worked fine. Thanks man. i appreciate the help.

**Comment by MichaelStott** [comment]
Closing issue for now, will update README as needed
