### ISSUE TITLE
Google Play Console Ad_Id

### ISSUE THREAD

**Issue by boyintheroom** [MichaelStott/KivMob#132]
Hi, does anyone know how this error can be fixed....im using kivmob rewarded ads 19.2.0 (cant use higher version as it doesnt support rewarded ads)
I have declared application id and gradle dependency in buildozer. But i dont see anything like Ad_Id in buildozer.
Api 33
![20230330_191141](https://user-images.githubusercontent.com/97958343/228868267-5cc34e98-83b9-4090-a29a-fa786d9f6066.jpg)

**Comment by mulivham** [comment]
i had the same issue last week .. check the link https://droidrocks.com/how-to-solve-you-must-complete-the-advertising-id-declaration-before-releasing-an-app-that-targets-android-13/

**Comment by boyintheroom** [comment]
@mulivham hi my friend thankyou for replying. How can i edit the manifest file permanently.

**Comment by mulivham** [comment]
first Unhide the hidden folders and go to  or find the path > .buildozer/android/platform/pythonforandroid/bootstraps/sdl2/build/templates  you will find the AndroidManifest file.

You can also use the Apktool from the Google Play store to edit the AndroidManifest by decompiling your app

**Comment by boyintheroom** [comment]
@mulivham Thankyou so much my friend. 🙏
