### ISSUE TITLE
python for android-admob not useable with newer APIs

### ISSUE THREAD

**Issue by thegameguy** [MichaelStott/KivMob#16]
The master branch of p4a is working just fine with sdk23 and ndkr16b, The code in bootstrap of p4a-admob is not similar to the code in p4a-master. If the sdl2-admob bootstrap is added to the p4a master version then kivmob is good to go with android API 26 or higher for now.

**Comment by MichaelStott** [comment]
I'll go ahead then update to the most recent p4a version for that branch. Hopefully, as this project matures, that branch won't be necessary.

Also, is this a different issue to the previous Python2 build error you reported?

**Comment by thegameguy** [comment]
yes, I got python2 build error because of the older version of p4a residing in p4a-admob. Luckily, the kivy vm 04 has up to date p4a with sdl2-admob bootstrap folder in it. but first, have to build with sdl2 bootstrap and sdl2-admob subsequently.

**Comment by thegameguy** [comment]
Hey Michael, could you please comment on this "PythonActivity$AdCmd". Is this a string or a decorator. The p4a code doesn't have this. The above mentioned code only arises when sdl2-admob bootstrap is used with p4a master.

**Comment by thegameguy** [comment]
Hoping to get revised p4a-admob soon.Thanks!

**Comment by thegameguy** [comment]
Hi again, I was wandering if I can help in updating p4a-admob?

**Comment by thegameguy** [comment]
Michael, apologies for my impatience, do we expect this issue to be resolved this week or when it is expected to be closed. 

Thanks!

**Comment by Petar-Luketina** [comment]
@thegameguy , have you figured anything out? I looked on this website, it looks like they did some work-arounds: http://quadropoly.com.au/kivy-and-admob-for-android-api-27/

**Comment by thegameguy** [comment]
@Petar-Luketina, that looks promising, I will give that a go and share if successful.

**Comment by Petar-Luketina** [comment]
@thegameguy  any luck? I couldn't get mine to work. Gonna keep trying

**Comment by yunus-ceyhan** [comment]
guys do you have any idea what would be happen to my existing apps on playstore after november 1 if don't adjust all for api 26? would all be suspended by google?

**Comment by thegameguy** [comment]
No the apps won't suspend that are below api 26 as long as they are live already but updates on the existing apps may be a problem there is a detailed explanation about it by google. your good with that

**Comment by yunus-ceyhan** [comment]
@thegameguy Thanks.

**Comment by irreverentperson** [comment]
Any updates for this? Has kiv mob been updated to support the admob update?

**Comment by MichaelStott** [comment]
I've gone ahead and pushed the changes in the KivMob 2.0 branch. There's still work that needs to be done, but these changes eliminate the need for a custom python-for-android branch and build with the latest Android APIs.

**Comment by thegameguy** [comment]
That is super awesome. Yayyyyy!
Please keep provision for my game “Gloworld” to be featured on kivmob. I will be incorporating Kivmob in day or two. Great!

**Comment by MichaelStott** [comment]
@thegameguy Sure, can you provide the playstore link?

**Comment by thegameguy** [comment]
https://play.google.com/store/apps/details?id=com.worldglowfree.dom.com.world.glowfree&hl=en
much obliged.

**Comment by MichaelStott** [comment]
@thegameguy Thanks, now listed in README.

**Comment by thegameguy** [comment]
Thanks a lot mate!

**Comment by yunus-ceyhan** [comment]
@MichaelStott Here are my apps using kivmob..

https://play.google.com/store/apps/details?id=com.ceyhan.sets

https://play.google.com/store/apps/details?id=com.ceyhan.tema

https://play.google.com/store/apps/details?id=com.prog.ders.eng
