### ISSUE TITLE
Admob ads not showing

### ISSUE THREAD

**Issue by irreverentperson** [MichaelStott/KivMob#19]
On the 27th of november, all ads stopped showing on my app. I use kivmob (because it's awesome by the way). 

I read the admob developer group forum and there are hundreds of people that started having the same problem around the same time. I haven't changed anything in my code.

Just wondering if you knew what was going on with Admob?

**Comment by MichaelStott** [comment]
After doing some further research, this appears to be an issue with AdMob unfortunately. Because KivMob is an independent open source project separate from AdMob itself, I can't offer any insight as to what might be happening. Closing for now.
