### ISSUE TITLE
ANR on large apps

### ISSUE THREAD

**Issue by JellyWX** [MichaelStott/KivMob#2]
I have a large app and I've attempted to integrate KivMob. KivMob however is inducing ANR for the app and I'm unsure why. I have integrated all the commands into purely the app's `build` method. No errors are being thrown by the application. The application successfully runs through the `build` and `on_start` methods before freezing

**Comment by MichaelStott** [comment]
Could you post the logcat output here? Also, how large is your application?

**Comment by JellyWX** [comment]
My logcat's playing up but I'll post what I can:
[out.txt](https://github.com/MichaelStott/KivMob/files/1222916/out.txt)

And, the application size in MB is around 15. Not that large, but I can't figure out what else could be killing KivMob. Our code is [here](https://github.com/swappt/blip-app)

**Comment by MichaelStott** [comment]
Thanks. Juggling a few things at the moment, but I'll try to get back to you sometime this week.

**Comment by MichaelStott** [comment]
Builds and runs fine for me when I changed the 'python' requirement to 'hostpython2' in buildozer.spec.

**Comment by MichaelStott** [comment]
Closing for now. Will reopen if notified that problem persists.

**Comment by JellyWX** [comment]
apologies, im away at the moment but ill have a look when im back. possible
i messed up the buildozer.spec. thanks
