### ISSUE TITLE
KivMob Documentation

### ISSUE THREAD

**Issue by MichaelStott** [MichaelStott/KivMob#21]
Write and publish KivMob documentation using Sphinx.

**Comment by irreverentperson** [comment]
hey Michael,
Any update on this? i've recloned kivy and rebuilt my program but it still wont show ads. can you ad an example in the .readme for how to do an ad and test ad? have kivmob commands changed in 2.0?
thanks!

**Comment by MichaelStott** [comment]
I should have a first version of the documentation up soon. I maintain this project in my spare time between my day job and other interests/projects, so updates and changes such as these aren't always forthcoming.

With regards to your issue, what kind of ads are you trying to display (banner, interstitial, or rewarded video)? The README does contain instructions for building an app that shows test interstitial ads. If that doesn't answer your question, feel free to open another issue with some example code and I'll try to help debug it.

**Comment by MichaelStott** [comment]
With regards to anything that changed, the only thing that comes to mind is the new_banner function (you just need to pass in the banner ID as a string without setting unitID in the function call). I'll include a more thorough changelog in the docs.

**Comment by irreverentperson** [comment]
thanks. i really appreciate your work here. 
i'm working with interstitials. i opened a new issue.

**Comment by MichaelStott** [comment]
This is finally complete: http://kivmob.com
