### ISSUE TITLE
pip install kivmod not working

### ISSUE THREAD

**Issue by Petar-Luketina** [MichaelStott/KivMob#34]
I couldn't update my kivmob, so I went into my directory and deleted the 2017 version. I did `pip install kivmob` and it won't work, as the image below shows.

How can I get the files from the zip into my directory?

![screenshot from 2019-01-20 18-44-17](https://user-images.githubusercontent.com/41878404/51446695-97b6bc00-1ce3-11e9-9ef1-7927c50da3f2.png)

**Comment by Petar-Luketina** [comment]
@MichaelStott , thank you. That worked perfectly! I still have `kivymd` to integrate with my PyCharm.

I downloaded the directory, unzipped it, did `sudo python ./setup.py install` in the directory, then added in PyCharm. I'm not sure what I have left to do.

If you have advice, please share. Otherwise, thank you again and we can close the case!

**Comment by MichaelStott** [comment]
For installing KivyMD, I just use the following:

`git+https://gitlab.com/kivymd/KivyMD.git`
