### ISSUE TITLE
Are ads supposed to be shown on bottom?

### ISSUE THREAD

**Issue by Petar-Luketina** [MichaelStott/KivMob#35]
Are the ads purposely set to be on the bottom? I checked the code (as seen below), and it seems like they're intended to be on the top but in your test app they appear on the bottom.
```
    def __init__(self, appID):
        Logger.info('KivMob: __init__ called.')
        self._banner_top_pos = True   # < this line?
```
Is there a way to bring them to the top?

**Comment by yunus-ceyhan** [comment]
@Petar-Luketina 

for to be shown on the top you dont have to change anytthin when you request ads.

```
self.new_banner("ca-app-pub-9581969.....")
```
for bottom just make top_pos = False

```
new_banner("ca-app-pub-95819......", top_pos = False )
```

**Comment by Petar-Luketina** [comment]
@yunus-ceyhan ah, yes. Now I see it in Michael's code: `self.ads.new_banner(TestIds.BANNER, False)`

Thank you kindly for the prompt response!
