### ISSUE TITLE
test ads not showing

### ISSUE THREAD

**Issue by irreverentperson** [MichaelStott/KivMob#36]
Hey Michael,
so here is a sample code. it worked before the admob update and subsequent kivmob update.
i've recloned kivmob and checked everything on my admob account....no joy.

```
from` kivy.app import App

from kivy.uix.scatter import Scatter
from kivy.uix.label import Label
from kivy.uix.floatlayout import FloatLayout 
from kivy.uix.textinput import TextInput 
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.button import Button
from kivy.storage.jsonstore import JsonStore
from kivy.uix.image import Image

import requests
from kivmob import KivMob, TestIds
from kivy.app import App
from kivy.uix.button import Button



class BasicApp(App):
	def build(self):
		def show(*args,**kwargs):
			self.ads.show_interstitial()	
		self.layout = FloatLayout()
		self.ads= KivMob(app_id)
		self.ads.add_test_device(test_device_id)
		self.ads.new_interstitial(interstitial_id)
		self.ads.request_interstitial()

		self.btn1 = Button(text = 'Gulf Coast', size_hint = (.49,.19), pos_hint = {'x':0,'y':.2}, on_release = show)
		self.layout.add_widget(self.btn1)

		return self.layout


		
if __name__ == '__main__':
	BasicApp().run()
```

**Comment by MichaelStott** [comment]
Difficult to say, could you post the logcat output?

`adb logcat | grep -E ".*/Ads|python"`

There are two things that might be the issue here:

1. Make sure that your are setting your app ID in the buildozer.spec file
`android.meta_data = com.google.android.gms.ads.APPLICATION_ID=APP_ID_HERE`
Also make sure that you're setting the other necessary properties in your buildozer.spec file. Check the README for more info.

2. It might take a while for your app to start receiving ads if you've recently set it up in AdMob.

**Comment by irreverentperson** [comment]
ok the spec is setup as specified in the readme.
now after buildozer android debug i get this error.

`` Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'pip install -q --user "appdirs" "colorama>=0.3.3" "sh>=1.10" "jinja2" "six"'
# Cwd None
You are using pip version 10.0.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
# Apache ANT found at /home/captain/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/captain/.buildozer/android/platform/android-sdk-24
# Android NDK is missing, downloading
# Downloading http://dl.google.com/android/ndk/android-ndk-r17b-linux-x86_64.bin
# Unpacking Android NDK
# Run 'chmod a+x android-ndk-r17b-linux-x86_64.bin'
# Cwd /home/captain/.buildozer/android/platform
# Run './android-ndk-r17b-linux-x86_64.bin'
# Cwd /home/captain/.buildozer/android/platform
./android-ndk-r17b-linux-x86_64.bin: 3: ./android-ndk-r17b-linux-x86_64.bin: Syntax error: newline unexpected
# Command failed: ./android-ndk-r17b-linux-x86_64.bin
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 
``

**Comment by MichaelStott** [comment]
I believe I had a similar issue when compiling after the buildozer update. As a workaround, try `buildozer dist clean`, removing the .buildozer folder in your local app directory, and  then rebuilding: `buildozer android debug`

**Comment by MichaelStott** [comment]
Closing for now. Will reopen if this is still an issue.
