### ISSUE TITLE
Error when creating apk

### ISSUE THREAD

**Issue by ArchyPeshenka** [MichaelStott/KivMob#37]
Trying to build apk for test project in readme, but have an error:

> Exception in thread background thread for pid 4640:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 2170, in background_thread
>     handle_exit_code(exit_code)
>   File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 1929, in fn
>     return self.command.handle_command_exit_code(exit_code)
>   File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
>     raise exc
> 
> ErrorReturnCode_1: 
>   RAN: ./gradlew assembleDebug
>   STDOUT:
> 
> FAILURE: Build failed with an exception.
> * What went wrong: 
> A problem occurred configuring root project 'fourscales'.
>  Could not resolve all dependencies for configuration ':_debugApkCopy'.
>    **Could not find com.google.firebase:firebase-ads:10.2.0.**
>      Required by:
>          project 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> BUILD FAILED
> Total time: 8.331 secs

What i'm doing wrong?

**Comment by MichaelStott** [comment]
Can you post your buildozer.spec file?

**Comment by ArchyPeshenka** [comment]
That's it: [click on me](https://yadi.sk/d/J-HjKIR3WxODgg)
I am using Buildozer 0.38.dev0 (Installed at Kivy complete VM by Zen-Code)

**Comment by MichaelStott** [comment]
Uncomment 'p4a.branch = master' and comment out p4a.source_dir.

Try specifying com.google.firebase:firebase-ads:10.2.0. instead of com.google.firebase:firebase-ads:17.1.3 in the spec file. You can also build with com.google.android.gms:play-services-ads:17.1.1 instead if you prefer.

**Comment by ArchyPeshenka** [comment]
There is strange problem now. Builds "Successfull", but rising Error and not creating apk. 

```
[DEBUG]:   	BUILD SUCCESSFUL in 11s
[DEBUG]:   	27 actionable tasks: 4 executed, 23 up-to-date

[INFO]:    <- directory context /home/kivy/Desktop/NewFolder/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Copying APK to current directory
[INFO]:    # APK filename not found in build output. Guessing...
[INFO]:    # Found APK file: /home/kivy/Desktop/NewFolder/.buildozer/android/platform/build/dists/fourscales/build/outputs/apk/debug/fourscales-debug.apk
[INFO]:    # Add version number to APK
[INFO]:    # APK renamed to fourscales-0.4.1-debug.apk
[DEBUG]:   -> running cp /home/kivy/Desktop/NewFolder/.buildozer/android/platform/build/dists/fourscales/build/outputs/apk/debug/fourscales-debug.apk fourscales-0.4.1-debug.apk
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No compiled python is present to zip, skipping.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
Warning: failed to apply patch (exit code 1), assuming it is already applied: src/patches/SDLActivity.java.patch
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer', 'console_scripts', 'buildozer')()
  File "/home/kivy/Repos/buildozer/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/kivy/Repos/buildozer/buildozer/__init__.py", line 1059, in run_command
    self.target.run_commands(args)
  File "/home/kivy/Repos/buildozer/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/kivy/Repos/buildozer/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/home/kivy/Repos/buildozer/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/home/kivy/Repos/buildozer/buildozer/targets/android.py", line 871, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/kivy/Desktop/NewFolder/.buildozer/android/platform/build/dists/fourscales/build/outputs/apk/fourscales-debug.apk'

```

**Comment by yunus-ceyhan** [comment]
your apk is in that directory, check it out.

/home/kivy/Desktop/NewFolder/.buildozer/android/platform/build/dists/fourscales/build/outputs/apk/debug/fourscales-debug.apk

**Comment by ArchyPeshenka** [comment]
Okay, I will try. I seen this file ,but I thought that it would not work, because the work on it is not yet complete.

**Comment by yunus-ceyhan** [comment]
my apk is always built in that directory as well. it works..

**Comment by ArchyPeshenka** [comment]
Yes! It works! Thanks for help =)
