### ISSUE TITLE
Android Ndk 17b issue

### ISSUE THREAD

**Issue by thegameguy** [MichaelStott/KivMob#39]
I am getting error while building with ndk 17b
Full log: https://pastebin.com/R0LiwV86
Thanks!

**Comment by thegameguy** [comment]
I am going to get ndk 17c. I hope its going to work with kivmob arrangment.

**Comment by MichaelStott** [comment]
Not sure what the issue is. Could you post the buildozer.spec file?

**Comment by thegameguy** [comment]
Unfortunately, kivent recipes have been deleted from latest P4a. That is a cheif issue for me in this case.

**Comment by MichaelStott** [comment]
Ah, sorry to hear that. This seems to be something the KivEnt maintainers will have to fix. Closing for now.

**Comment by thegameguy** [comment]
Hi, confirming the ndk 17c works with kivmob. Just catching up !!!!!!!!!
