### ISSUE TITLE
Not an issue, just want to add my app built with KivMob into App Showcase in README and doc.

### ISSUE THREAD

**Issue by jacklinquan** [MichaelStott/KivMob#41]
Hi Michael,

Thank you a lot for KivMob. It is amazing and easy to use.
Here's my app built with it:
App: PyTool USB Serial Free
Play Store Link: https://play.google.com/store/apps/details?id=com.quanlin.pytoolusbserialfree
Author: Quan Lin

Best regards,
Quan

**Comment by MichaelStott** [comment]
Glad you like it! Your app is now listed in the README.
