### ISSUE TITLE
About App_ID

### ISSUE THREAD

**Issue by abdullahrss** [MichaelStott/KivMob#51]
Hi, i have a simple question this confused me 
> APPLICATION_ID

`android.meta_data = com.google.android.gms.ads.APPLICATION_ID=` which is must i use  ad unit id (admob interstitial id ) or google play store app id ?

**Comment by MichaelStott** [comment]
That would be the AdMob application ID, you would set it there in buildozer.spec and in the KivMob constructor. See https://support.google.com/admob/answer/7356431?hl=en for more information on where to find that value.
