### ISSUE TITLE
About ads and test ads

### ISSUE THREAD

**Issue by abdullahrss** [MichaelStott/KivMob#52]
Hi, I have app on play store. All of the ads that appeared on my app are test ads. Why doesn't normal ad appear ?
.spec file
`android.gradle_dependencies ='com.google.firebase:firebase-ads:18.2.0'`
`android.meta_data = com.google.android.gms.ads.APPLICATION_ID=ca-app-pub-MyID`

related main.py
```
def build(self):
        self.ads = KivMob(TestIds.APP)
        self.ads.new_interstitial(TestIds.INTERSTITIAL)
        self.ads.request_interstitial()
        ....
def show_interstitial(self):
        self.ads.show_interstitial()
```

I call the function in kv lang like `app. show_interstitial()`

Does the test ad appear because I write `TestIds.APP` or `TestIds.INTERSTITIAL`  ? Should I write something else ?

**Comment by MichaelStott** [comment]
That's exactly right.TestIds is meant to quickly test displaying ads. You need to replace those values with your actual app ID and interstitial ID in production.
