### ISSUE TITLE
issue in Ubuntu after installing kivMob

### ISSUE THREAD

**Issue by aliboumrah** [MichaelStott/KivMob#53]
Hello,
after installing kimob with : pip3 install kivmob.
python3 is not finding any window rovider in ubuntu 18.04, and shows thi error : 
![image](https://user-images.githubusercontent.com/30910103/65188124-95208800-da65-11e9-819d-28ef9dde3759.png)

I have python2 in the same but without kivmob, and with it I have no issue.

Regards

**Comment by MichaelStott** [comment]
This seems like an issue with your Kivy installation, not KivMob. Does this help?

https://github.com/kivy/kivy/issues/6071

**Comment by aliboumrah** [comment]
I resolved the issue by using a virtual environment.
Thank you for taking the time and sharing with me that link

**Comment by MichaelStott** [comment]
Glad to hear you resolved it. Happy coding!

**Comment by muradddd** [comment]
Actually, I have the same probem. How can i solve this?
