### ISSUE TITLE
Test Banner

### ISSUE THREAD

**Issue by Ayhancelik** [MichaelStott/KivMob#55]
Hi Michael First of all, thank you.
I'm new to software development , python and kivy.
I have prepared and published an application called Password Builder.
He's testing it right now. Even though I put my own number in the code.
Should I wait for a while or is there something wrong?
Should I write something else instead of TestIds?

self.ads = KivMob(TestIds.APP)
self.ads.new_banner(TestIds.BANNER, top_pos= False)
self.ads.request_banner()
self.ads.show_banner()
Do I need a change in code?

As your tutorials like
I Have added my application id to the spec file .
https://play.google.com/store/apps/details?id=com.passwordbuilder.passwordbuilder

**Comment by MichaelStott** [comment]
You need to pass in App ID and Banner ID from AdMob into the KivMob constructor and the new_banner method. TestIds.APP and TestIds.BANNER refer to a set of test ids provided by AdMob.
```python
# TestIds.APP
APP = "ca-app-pub-3940256099942544~3347511713"

# TestIds.BANNER
BANNER = "ca-app-pub-3940256099942544/6300978111"
```
So in your code, you would want to replace the TestId values with ones you created in your AdMob account.
```python
self.ads = KivMob('ca-app-pub-INSERT-YOUR-APP-ID-HERE')
self.ads.new_banner('ca-app-pub-INSERT-YOUR-BANNER-ID-HERE', top_pos= False)
```

**Comment by Ayhancelik** [comment]
:) = My fake app-id =  ca-app-pub-112312312312312312123123
:) = My fake banner-id = ca-app-pub-7567567567567567567567567

*************************************************
class uic(App):
	
	def build(self):
		self.ads = KivMob('ca-app-pub-112312312312312312123123')
		self.ads.new_banner('ca-app-pub-7567567567567567567567567', top_pos= False)
		self.ads.request_banner()
		self.ads.show_banner()

		self.marea = marea()
		return self.marea
		
     	
if __name__ == "__main__":
	uic().run()

*************************************************


I did try this code on my tablet.
But I didn't get a result. There's no banner, no warning, nothing.
I'm doing something wrong.
Like I said, I'm a rookie. :(

**Comment by MichaelStott** [comment]
:+1: for using fake AdMob ids. 

hmm... there are two other things I can think of here. The first is that maybe the app id isn't set in the buildozer.spec file. The other is that AdMob may not yet be serving live ads to your application. For some people, it can take as long as one to two days for them to start receiving live, non-test ads.

Can you confirm that you can display test ads? If so, then I think that's the issue is that AdMob simply isn't sending any ads at this time. If test ads are not displaying, can you confirm that logcat isn't showing any AdMob related errors? The below command will output any logcat messages related to your kivy app when your device is connected.
```
$ adb logcat | grep -E ".*/Ads|python"
```

It also never hurts to post your buildozer.spec file with the AdMob app Id redacted.

**Comment by Ayhancelik** [comment]
Buildozer completes the operation. and output apk. No problem with that but..
I get a warning from Buildozer.
# Package the application
# Asking for release but P4A_RELEASE_KEYALIAS is missing--sign will not be passed
# Asking for release but P4A_RELEASE_KEYSTORE_PASSWD is missing--sign will not be passed
# Asking for release but P4A_RELEASE_KEYSTORE is missing--sign will not be passed
# Asking for release but P4A_RELEASE_KEYALIAS_PASSWD is missing--sign will not be passed
Can we solve the signing and admob test confirmation work with the sections we write in buildozer spec file???

This is OK. no problem with that.: "It also never hurts to post your buildozer.spec file with the AdMob app id redacted."
That section is as follows ::
android.meta_data = com.google.android.gms.ads.APPLICATION_ID=ca-app-pub-1123123123123123121231237

**Comment by Ayhancelik** [comment]
I can't see it on my own tablet, but when I put it into the system and it was approved, the ads started to appear.
Thank you..
May the force be with you. :)

**Comment by MichaelStott** [comment]
And also with you :+1: :)
