### ISSUE TITLE
Banner doesn't work

### ISSUE THREAD

**Issue by cagricuhadaroglucc** [MichaelStott/KivMob#56]
Thanks for your Kivmob

I haven't get an error but log, banner doesn't show.
My admob account is active. i got a mail

my main code

Builder.load_string(DrawerMainStr)

if __name__ == '__main__':
    navigationdrawer = NavigationDrawer()    

        ####Main Panel####

    def build(self):
            
            self.ads = KivMob("ca-app-pub-118295508")
            self.ads.new_banner({"unitID": "ca-app-pub-11829550818"})
            self.ads.request_banner()
            self.ads.show_banner()
        

    def show_banner(self,*args):
            self.ads.show_banner()

    def adv_load():

        

        layout1=BoxLayout(orientation="vertical")
        advImg1=Button(background_normal=('Adv/1.png'),
                  background_down=('Adv/1.png'),size_hint=(1,.20))
        
        layout1.add_widget(advImg1)
        advImg=Button(background_normal=('Img/1.png'),
                  background_down=('Img/1.png'),size_hint=(1,.60))
        layout1.add_widget(advImg)
        sldImg=Button(background_normal=('Img/2.png'),
                  background_down=('Img/2.png'),size_hint=(1,.20))      
        layout1.add_widget(sldImg)
        return layout1

    main_panel=adv_load()   

    def load_module_GUI(module_name):
        navigationdrawer.anim_to_state('closed')        
        global main_panel
        module_to_import="Modules."+module_name
        imported_module=__import__(module_to_import, globals(), locals(), ["moduleGUI()"])
        module_layout=imported_module.moduleGUI()
        navigationdrawer.remove_widget(main_panel)
        main_panel=module_layout
        navigationdrawer.set_main_panel(main_panel)

    ####Side Panel####
    
    layout2 = GridLayout(cols=1,size_hint_y=None,height=dp(1600))    
    layout2.add_widget(Button(size_hint_y=None,height=dp(160),background_normal=('Img/3.png'),
                  background_down=('Img/3.png')))
    Alpek_button = Button(background_normal=('Img/6.png'),size_hint_y=None,height=dp(80))
    Alpek_button.bind(on_release=lambda j:load_module_GUI('Alpek'))
    layout2.add_widget(Alpek_button) 
    
    scrollview1 = ScrollView(bar_width='8dp',do_scroll_x=False)
    scrollview1.add_widget(layout2)
    side_panel=scrollview1

    navigationdrawer.add_widget(side_panel)
    navigationdrawer.add_widget(main_panel)   

    Window.add_widget(navigationdrawer)    
    
    runTouchApp()

i only noticed this argument

CANNOT LINK EXECUTABLE "/system/bin/dpmd": "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit

but my app is working without banner

**Comment by cagricuhadaroglucc** [comment]
my log
[log.docx](https://github.com/MichaelStott/KivMob/files/3883104/log.docx)


my spec

# (str) Application versioning (method 1)
#version.regex = __version__ = '(.*)'
#version.filename = %(source.dir)s/main.py
version = 0.1
# (str) Application versioning (method 2)
#version = 1.18

# (list) Application requirements-- hostpython3,python3,hostpython2,
requirements =  kivy,jnius, kivmob

# (str) Presplash of the application
presplash.filename = %(source.dir)s/presplash.png

# (str) Icon of the application
icon.filename = %(source.dir)s/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (list) Permissions
android.permissions = INTERNET,ACCESS_NETWORK_STATE

# (int) Android API to use
android.api = 27

# (int) Minimum API required (8 = Android 2.2 devices)
android.minapi = 21

# (int) Android SDK version to use
android.sdk = 24

# (str) Android NDK version to use
android.ndk = 17b

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path = 

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#android.p4a_dir =

android.gradle_dependencies = 'com.google.firebase:firebase-ads:10.2.0'

p4a.branch = master

android.meta_data = com.google.android.gms.ads.APPLICATION_ID={ca-app-pub-118295508}

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

**Comment by cagricuhadaroglucc** [comment]
11-24 02:32:05.840 10816 10816 F linker  : CANNOT LINK EXECUTABLE "/system/bin/dpmd": "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit
11-24 02:32:06.675  2274  2372 I MobileSignalController: mCurrentState.dataConnected--> false mCurrentState.connected--> true mDataState--> 0 mMMSDataState--> DISCONNECTED
CANNOT LINK EXECUTABLE "/system/bin/dpmd": "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit

is could be the error code

**Comment by MichaelStott** [comment]
Are you using the latest version of KivMob (2.0)? The correct way of creating a new banner object is like so:

```python
self.ads.new_banner("INSERT-YOUR-BANNER-ID-HERE")
```

**Comment by cagricuhadaroglucc** [comment]
How can i get kivmob version information

**Comment by MichaelStott** [comment]
Try this:
```bash
$ pip3 show kivmob
```

**Comment by cagricuhadaroglucc** [comment]
kivmob 2.0

**Comment by cagricuhadaroglucc** [comment]
11-24 22:56:38.213   832   832 E SurfaceFlinger: [SurfaceView - .gmail.com.myapp/org.kivy.android.PythonActivity#0] rejecting buffer: bufWidth=1080, bufHeight=1977, front.active.{w=1080, h=2160}
11-24 22:56:39.255  2283  2392 I MobileSignalController: mCurrentState.dataConnected--> false mCurrentState.connected--> true mDataState--> 0 mMMSDataState--> DISCONNECTED
11-24 22:56:41.560  2621  4608 I DPMJ    : |REQ:RCVR| DPM creating socket
11-24 22:56:42.952 21598 21598 F linker  : CANNOT LINK EXECUTABLE "/system/bin/dpmd": "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit
could be the error

**Comment by cagricuhadaroglucc** [comment]
My main.py

#-*-coding:utf-8-*-

from kivmob import KivMob  ###ADMOB GOOGLE###

from kivy.app import App
from kivy.base import runTouchApp,stopTouchApp
from kivy.uix.button import Button
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.image import Image
from kivy.uix.scrollview import ScrollView
from kivy.core.window import Window
from kivy.metrics import dp
from kivy.lang import Builder
from kivy.utils import platform


from drawer import NavigationDrawerException,NavigationDrawer,DrawerMainStr




Builder.load_string(DrawerMainStr)



if __name__ == '__main__':
    navigationdrawer = NavigationDrawer()    

        ####Main Panel####

    

    


    def adv_load():

        def build(self):
            
            self.ads = KivMob("ca-app-pub-1182955081")
            self.ads.new_banner("ca-app-pub-11829550")
            self.ads.request_banner()
            self.ads.show_banner()
        

        def show_banner(self,*args):
            self.ads.show_banner()


        def on_resume(self):
            self.ads.show_banner()

        def on_start(self):
            self.ads.show_banner()

        

        layout1=BoxLayout(orientation="vertical")
        advImg1=Button(background_normal=('Adv/1.png'),
                  background_down=('Adv/1.png'),size_hint=(1,.20))
        
        layout1.add_widget(advImg1)
        advImg=Button(background_normal=('Img/1.png'),
                  background_down=('Img/1.png'),size_hint=(1,.60))
        advImg.bind(on_release=lambda j:show_banner("ca-app-pub-118295508"))###
        layout1.add_widget(advImg)
        sldImg=Button(background_normal=('Img/2.png'),
                  background_down=('Img/2.png'),size_hint=(1,.20))      
        layout1.add_widget(sldImg)
        return layout1

    main_panel=adv_load()   

    def load_module_GUI(module_name):
        navigationdrawer.anim_to_state('closed')        
        global main_panel
        module_to_import="Modules."+module_name
        imported_module=__import__(module_to_import, globals(), locals(), ["moduleGUI()"])
        module_layout=imported_module.moduleGUI()
        navigationdrawer.remove_widget(main_panel)
        main_panel=module_layout
        navigationdrawer.set_main_panel(main_panel)

    ####Side Panel####
    
    layout2 = GridLayout(cols=1,size_hint_y=None,height=dp(1600))    
    layout2.add_widget(Button(size_hint_y=None,height=dp(160),background_normal=('Img/3.png'),
                  background_down=('Img/3.png')))
    Alpek_button = Button(background_normal=('Img/6.png'),size_hint_y=None,height=dp(80))
    Alpek_button.bind(on_release=lambda j:load_module_GUI('Alpek'))
    layout2.add_widget(Alpek_button)
    LVCable_button = Button(background_normal=('Img/4.png'),size_hint_y=None,height=dp(80))
    LVCable_button.bind(on_release=lambda j:load_module_GUI('LVCable'))
    layout2.add_widget(LVCable_button)
    LVCFind_button = Button(background_normal=('Img/15.png'),size_hint_y=None,height=dp(80))
    LVCFind_button.bind(on_release=lambda j:load_module_GUI('LVCFind'))
    layout2.add_widget(LVCFind_button)
    LVCT_button = Button(background_normal=('Img/16.png'),size_hint_y=None,height=dp(80))
    LVCT_button.bind(on_release=lambda j:load_module_GUI('LVCT'))
    layout2.add_widget(LVCT_button)
    AlCuBars_button = Button(background_normal=('Img/5.png'),size_hint_y=None,height=dp(80))
    AlCuBars_button.bind(on_release=lambda j:load_module_GUI('CuAlBars'))
    layout2.add_widget(AlCuBars_button)    
    ConPole_button = Button(background_normal=('Img/7.png'),size_hint_y=None,height=dp(80))
    ConPole_button.bind(on_release=lambda j:load_module_GUI('ConPole'))
    layout2.add_widget(ConPole_button)
    IroPole_button = Button(background_normal=('Img/8.png'),size_hint_y=None,height=dp(80))
    IroPole_button.bind(on_release=lambda j:load_module_GUI('IroPole'))
    layout2.add_widget(IroPole_button)
    Gen_button = Button(background_normal=('Img/14.png'),size_hint_y=None,height=dp(80))
    Gen_button.bind(on_release=lambda j:load_module_GUI('Gen'))
    layout2.add_widget(Gen_button)
    VDropD_button = Button(background_normal=('Img/9.png'),size_hint_y=None,height=dp(80))
    VDropD_button.bind(on_release=lambda j:load_module_GUI('VDropD'))
    layout2.add_widget(VDropD_button)
    ASec_button = Button(background_normal=('Img/18.png'),size_hint_y=None,height=dp(80))
    ASec_button.bind(on_release=lambda j:load_module_GUI('ASec'))
    layout2.add_widget(ASec_button)
    ALine_button = Button(background_normal=('Img/19.png'),size_hint_y=None,height=dp(80))
    ALine_button.bind(on_release=lambda j:load_module_GUI('ALine'))
    layout2.add_widget(ALine_button)
    MCond_button = Button(background_normal=('Img/20.png'),size_hint_y=None,height=dp(80))##add pic
    MCond_button.bind(on_release=lambda j:load_module_GUI('MCond'))
    layout2.add_widget(MCond_button)
    PCorrect_button = Button(background_normal=('Img/10.png'),size_hint_y=None,height=dp(80))
    PCorrect_button.bind(on_release=lambda j:load_module_GUI('PCorrect'))
    layout2.add_widget(PCorrect_button)
    MVCable_button = Button(background_normal=('Img/13.png'),size_hint_y=None,height=dp(80))
    MVCable_button.bind(on_release=lambda j:load_module_GUI('MVCable'))
    layout2.add_widget(MVCable_button)
    MVTrans_button = Button(background_normal=('Img/11.png'),size_hint_y=None,height=dp(80))
    MVTrans_button.bind(on_release=lambda j:load_module_GUI('MVTrans'))
    layout2.add_widget(MVTrans_button)
    Motor_button = Button(background_normal=('Img/17.png'),size_hint_y=None,height=dp(80))
    Motor_button.bind(on_release=lambda j:load_module_GUI('Motor'))
    layout2.add_widget(Motor_button)
    exit_button = Button(background_normal=('Img/12.png'),size_hint_y=None,height=dp(80))
    ###exit_button.bind(on_release=lambda j:stopTouchApp())
    exit_button.bind(on_release=lambda j:show_banner())
    layout2.add_widget(exit_button) 
    info_button = Button(background_normal=('Img/12.png'),size_hint_y=None,height=dp(80))
    info_button.bind(on_release=lambda j:load_module_GUI('Info'))
    layout2.add_widget(info_button)    
    
    scrollview1 = ScrollView(bar_width='8dp',do_scroll_x=False)
    scrollview1.add_widget(layout2)
    side_panel=scrollview1



    navigationdrawer.add_widget(side_panel)
    navigationdrawer.add_widget(main_panel)   

    Window.add_widget(navigationdrawer)    
    
    runTouchApp()

**Comment by cagricuhadaroglucc** [comment]
requirements =  kivy,jnius, kivmob,python3,android (i set it  like this)

when i add hostpython2,

i cat this error and it is crashes

I python  :  ImportError: dlopen failed: library "libpython3.7m.so" not found

**Comment by MichaelStott** [comment]
You shouldn't need to add both hostpython2 and python3 in this instance, just one or the other depending on which python version your project uses. From your buildozer.spec file, it looks like you are using python3.

As for the the "libpython3.7m.so not found error" I'm not entirely sure, it looks like buildozer issue where it can't find the python3 library. I would try a `buildozer clean` and try again.

**Comment by cagricuhadaroglucc** [comment]
i have solved the issue by using only python3, but now showing ads too.

Because i have no  "class ....... (App) code" in my main.py

i have "Builder.load_string(DrawerMainStr)
             runTouchApp()"

i have no class def in my main where should i add the code

**Comment by MichaelStott** [comment]
If you make the KivMob calls sometime before you call runTouchApp, I believe it should work.

**Comment by cagricuhadaroglucc** [comment]
i must def class a and import touch app into it is it posible

**Comment by MichaelStott** [comment]
If your class inherits from Widget in some way then yes, I believe so. If you want to use the App class that Kivy provides, you will need to refactor.

I feel we're getting slightly off topic here. Let me know if you have KivMob specific questions. If you need more help with your application, I would try going to StackOverflow or some coding forum.

**Comment by MichaelStott** [comment]
Closing for now. Let me know if you encounter any other issues.

**Comment by cagricuhadaroglucc** [comment]
i have no issue at now thks
