### ISSUE TITLE
Banner Ad Positioning

### ISSUE THREAD

**Issue by Ayhancelik** [MichaelStott/KivMob#57]
Hi again Michael
Is it possible to place the banner anywhere?
Could you for example into a Popup ?

**Comment by MichaelStott** [comment]
Not at this time. I don't think there would be any way of attaching the banner ad to a Kivy widget, as the banner ad rendering is handled by the Android view logic. It _could_ be possible to position and size a banner ad such that it could appear over a widget, but that functionality is currently not exposed.

**Comment by Ayhancelik** [comment]
Ok Thnks
