### ISSUE TITLE
closing banner admob-question

### ISSUE THREAD

**Issue by cagricuhadaroglucc** [MichaelStott/KivMob#58]
how can i close banner
class MyAPP(App):
    def build(self):            
        self.ads = KivMob(TestIds.APP)
        self.ads.new_banner(TestIds.BANNER, top_pos=True)
        self.ads.request_banner()
        self.ads.show_banner()
        return navigationdrawer

Alpek_button = Button(background_normal=('Img/6.png'),size_hint_y=None,height=dp(80))
Alpek_button.bind(on_release=lambda j:load_module_GUI('Alpek'),MyAPP.ads.hide_banner())

**Comment by cagricuhadaroglucc** [comment]
And another question,
banner size rendered as "percentage of screen" or "constant pixel size as height"

**Comment by MichaelStott** [comment]
Hi @cagricuhadaroglucc, you should be able to use hide_banner to "close" the banner ad. If you want to remove the underlying banner object, you can call destroy_banner.

For sizing, KivMob uses the SMART_BANNER size: https://developers.google.com/admob/android/banner/smart
