### ISSUE TITLE
How do I use interstitial in a function?

### ISSUE THREAD

**Issue by Ayhancelik** [MichaelStott/KivMob#59]
Hi Michael

I'm still using this type of ad in an active application, but I still haven't been able to resolve some things.

Can I use this type of ad this way by throwing it into a class to invoke it at any time?

```
def interstil(self):
           self.ads = KivMob('ca-app-pub-0100111010100110110101')
           self.ads.new_interstitial('ca-app-pub-0100111010100110110101')
           self.ads.request_interstitial()
           self.ads.show_interstitial()
		
            def on_resume(self):
                       self.ads.request_interstitial()
```

**Comment by MichaelStott** [comment]
I wouldn't instantiate KivMob or the interstitial every time that you call an object. on_resume is a method specific to the App class, so your interstitial ad will never reload in this case.

Generally, I like to instantiate KivMob as a property of the app class and then, if I need to access KivMob from a widget or some other class/module, use App.get_running_app() to access it.
