### ISSUE TITLE
Cython Compiling Error

### ISSUE THREAD

**Issue by arctia92** [MichaelStott/KivMob#6]
Compiling The Demo Fail with a Cython error:

buildozer: 0.34
cython: 0.25.2

`[INFO]:    kivy first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize kivy/weakproxy.pyx
[INFO]:    -> running cython ./kivy/weakproxy.pyx
[INFO]:    Cythonize kivy/properties.pyx
[INFO]:    -> running cython ./kivy/properties.pyx
[INFO]:    Cythonize kivy/_event.pyx
[INFO]:    -> running cython ./kivy/_event.pyx
[INFO]:    Cythonize kivy/_clock.pyx
[INFO]:    -> running cython ./kivy/_clock.pyx
[INFO]:    Cythonize kivy/lib/vidcore_lite/bcm.pyx
[INFO]:    -> running cython ./kivy/lib/vidcore_lite/bcm.pyx
[INFO]:    Cythonize kivy/lib/vidcore_lite/egl.pyx
[INFO]:    -> running cython ./kivy/lib/vidcore_lite/egl.pyx
[INFO]:    Cythonize kivy/lib/gstplayer/_gstplayer.pyx
[INFO]:    -> running cython ./kivy/lib/gstplayer/_gstplayer.pyx
[INFO]:    Cythonize kivy/graphics/opengl_utils.pyx
[INFO]:    -> running cython ./kivy/graphics/opengl_utils.pyx
[INFO]:    Cythonize kivy/graphics/opengl.pyx
[INFO]:    -> running cython ./kivy/graphics/opengl.pyx
[INFO]:    Cythonize kivy/graphics/cgl.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl.pyx
[INFO]:    Cythonize kivy/graphics/compiler.pyx
[INFO]:    -> running cython ./kivy/graphics/compiler.pyx
[INFO]:    Cythonize kivy/graphics/shader.pyx
[INFO]:    -> running cython ./kivy/graphics/shader.pyx
[INFO]:    Cythonize kivy/graphics/gl_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/gl_instructions.pyx
[INFO]:    Cythonize kivy/graphics/transformation.pyx
[INFO]:    -> running cython ./kivy/graphics/transformation.pyx
[INFO]:    Cythonize kivy/graphics/buffer.pyx
[INFO]:    -> running cython ./kivy/graphics/buffer.pyx
[INFO]:    Cythonize kivy/graphics/texture.pyx
[INFO]:    -> running cython ./kivy/graphics/texture.pyx
[INFO]:    Cythonize kivy/graphics/context_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/context_instructions.pyx
[INFO]:    Cythonize kivy/graphics/context.pyx
[INFO]:    -> running cython ./kivy/graphics/context.pyx
[INFO]:    Cythonize kivy/graphics/instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/instructions.pyx
[INFO]:    Cythonize kivy/graphics/vertex_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/vertex_instructions.pyx
[INFO]:    Cythonize kivy/graphics/fbo.pyx
[INFO]:    -> running cython ./kivy/graphics/fbo.pyx
[INFO]:    Cythonize kivy/graphics/vertex.pyx
[INFO]:    -> running cython ./kivy/graphics/vertex.pyx
[INFO]:    Cythonize kivy/graphics/tesselator.pyx
[INFO]:    -> running cython ./kivy/graphics/tesselator.pyx
[INFO]:    Cythonize kivy/graphics/stencil_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/stencil_instructions.pyx
[INFO]:    Cythonize kivy/graphics/vbo.pyx
[INFO]:    -> running cython ./kivy/graphics/vbo.pyx
[INFO]:    Cythonize kivy/graphics/svg.pyx
[INFO]:    -> running cython ./kivy/graphics/svg.pyx
[INFO]:    Cythonize kivy/graphics/scissor_instructions.pyx
[INFO]:    -> running cython ./kivy/graphics/scissor_instructions.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_sdl2.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_sdl2.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_mock.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_mock.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_debug.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_debug.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_gl.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_gl.pyx
[INFO]:    Cythonize kivy/graphics/cgl_backend/cgl_glew.pyx
[INFO]:    -> running cython ./kivy/graphics/cgl_backend/cgl_glew.pyx
[INFO]:    Cythonize kivy/core/camera/camera_avfoundation.pyx
[INFO]:    -> running cython ./kivy/core/camera/camera_avfoundation.pyx
[INFO]:    Cythonize kivy/core/window/window_info.pyx
[INFO]:    -> running cython ./kivy/core/window/window_info.pyx
[INFO]:    Cythonize kivy/core/window/_window_sdl2.pyx
[INFO]:    -> running cython ./kivy/core/window/_window_sdl2.pyx
[INFO]:    Cythonize kivy/core/window/window_x11.pyx
[INFO]:    -> running cython ./kivy/core/window/window_x11.pyx
()                                                                                                                                                                     
           working:     def get_window_info(self):                                                             Exception in thread background thread for pid 20779:    
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/arctia/.local/lib/python2.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/arctia/.local/lib/python2.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/arctia/.local/lib/python2.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/arctia/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_1: 

  RAN: /usr/local/bin/cython ./kivy/core/window/window_x11.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.config import Config
from kivy.base import stopTouchApp, EventLoop, ExceptionManager
from kivy.utils import platform
from os import environ

from window_info cimport WindowInfoX11
^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:18:0: 'kivy/core/window/window_info/WindowInfoX11.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
cdef extern int x11_create_window(int width, int height, int x, int y, \
        int resizable, int fullscreen, int border, int above, int CWOR, char *title)
cdef extern void x11_gl_swap()
cdef extern void x11_set_title(char *title)
cdef extern int x11_idle()
cdef extern Display *x11_get_display()
           ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:69:12: 'Display' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        int resizable, int fullscreen, int border, int above, int CWOR, char *title)
cdef extern void x11_gl_swap()
cdef extern void x11_set_title(char *title)
cdef extern int x11_idle()
cdef extern Display *x11_get_display()
cdef extern Window x11_get_window()
           ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:70:12: 'Window' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.system_size = size
        super(WindowX11, self).create_window()
        self._unbind_create_window()

    def get_window_info(self):
        cdef WindowInfoX11 window_info = WindowInfoX11()
            ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:221:13: 'WindowInfoX11' is not a type identifier

  STDERR:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/arctia/utilities/p4a/pythonforandroid/toolchain.py", line 903, in <module>
    main()
  File "/home/arctia/utilities/p4a/pythonforandroid/toolchain.py", line 900, in main
    ToolchainCL()
  File "/home/arctia/utilities/p4a/pythonforandroid/toolchain.py", line 508, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/arctia/utilities/p4a/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/arctia/utilities/p4a/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 564, in build_recipes
  File "pythonforandroid/recipe.py", line 975, in build_arch
  File "pythonforandroid/recipe.py", line 1010, in build_cython_components
  File "/home/arctia/utilities/p4a/pythonforandroid/recipes/kivy/__init__.py", line 18, in cythonize_build
    super(KivyRecipe, self).cythonize_build(env, build_dir=build_dir)
  File "pythonforandroid/recipe.py", line 1055, in cythonize_build
  File "pythonforandroid/recipe.py", line 1046, in cythonize_file
  File "pythonforandroid/logger.py", line 175, in shprint
  File "/home/arctia/.local/lib/python2.7/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/arctia/.local/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/arctia/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/cython ./kivy/core/window/window_x11.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.config import Config
from kivy.base import stopTouchApp, EventLoop, ExceptionManager
from kivy.utils import platform
from os import environ

from window_info cimport WindowInfoX11
^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:18:0: 'kivy/core/window/window_info/WindowInfoX11.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
cdef extern int x11_create_window(int width, int height, int x, int y, \
        int resizable, int fullscreen, int border, int above, int CWOR, char *title)
cdef extern void x11_gl_swap()
cdef extern void x11_set_title(char *title)
cdef extern int x11_idle()
cdef extern Display *x11_get_display()
           ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:69:12: 'Display' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        int resizable, int fullscreen, int border, int above, int CWOR, char *title)
cdef extern void x11_gl_swap()
cdef extern void x11_set_title(char *title)
cdef extern int x11_idle()
cdef extern Display *x11_get_display()
cdef extern Window x11_get_window()
           ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:70:12: 'Window' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.system_size = size
        super(WindowX11, self).create_window()
        self._unbind_create_window()

    def get_window_info(self):
        cdef WindowInfoX11 window_info = WindowInfoX11()
            ^
------------------------------------------------------------

kivy/core/window/window_x11.pyx:221:13: 'WindowInfoX11' is not a type identifier

  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2-admob --requirements=kivy,hostpython2,android,kivmob --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/arctia/Desktop/Tree/games/kivmobtest/KivMob-master/demo/.buildozer/android/platform/build                      
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2`

**Comment by yunus-ceyhan** [comment]
i faced with the same issue but i was able to fix it. 

first change your app package name, then compile your script normally without any change in buildozer.spech except its requirements. it will install requirements without any error as well as cython. however i suggest you use command "buildozer android clean" first.  when you compile your app successfully then edit your buildozer as describe here, change your app's package name as you want and compile it in the same project folder. it should work.

**Comment by arctia92** [comment]
Thank you very much, now it's working. A little more thing, i have problem displaying test ads with my test device id i get real ads, have you managed to display them?
(in the past i got them working correctly..)

**Comment by yunus-ceyhan** [comment]
i havent tried test ad so far. instead i added my test device and get real ads as you mentioned.

Why do you want the test ads on your test device? if you once add your test device id then it doesn't matter if you even click on real ads on your test device because admob will not count those clicks. so dont worry, your account will not be suspended.

**Comment by arctia92** [comment]
Ok that's a good answer, I really appreciate your help. Keep up the good work ;)
