### ISSUE TITLE
my app for child

### ISSUE THREAD

**Issue by BeratErtugrul** [MichaelStott/KivMob#60]
I published a game in playstore my new app https://play.google.com/store/apps/details?id=org.tosbikod.tosbikod  .I want to use kivmob banner and intersititial. tested my app before test id. it works very well. but any time didn't work my banner and intersitial id .  I discover my app for child usages so i need to arrenge this app for "child" and "family" usages but i  dont have any idea.Kivmob does support this situation? and how can do it?

**Comment by MichaelStott** [comment]
This is possible, but I've just realized that I don't have that feature listed in the docs :frowning_man: 

What you would do is pass in additional options with a dictionary and pass that into your request_banner/request_interstitial functions.

For example: 
```
kivmob.request_banner({"family": True, "children":  True})
```
