### ISSUE TITLE
Smart Banner ad height in dp

### ISSUE THREAD

**Issue by yunus-ceyhan** [MichaelStott/KivMob#61]
Hi Michael,

Just want to know if is it possible to get the height of the smart banner in dp?

I need to resize some of widgets before showing the banner. 

if it's possible for available kivmob version how? if it's not then what i need to add the kivmob.py to get that result?

**Comment by MichaelStott** [comment]
The module doesn't offer this functionality at this time, but it should be simple enough to add I would think. Will look into it.

**Comment by MichaelStott** [comment]
@yunus-ceyhan A helper function is now available, `determine_banner_height`, that determines the height of the banner ad based on the screen height.

**Comment by yunus-ceyhan** [comment]
Thank you so much for your efforts. 👍

**Comment by blufips** [comment]
Good day I try to use determine_banner_height but I'm having AttributeError: 'KivMob' Object has no attribute determine_banner_height

**Comment by blufips** [comment]
I check my kivmob.py and i did not see any attribute determine_banner_height. I wonder how I include this in buildozer requirements

**Comment by blufips** [comment]
I just include the kivmob.py in my main directories and remove it in requirements. Its now working
Thank you for the wonderful module

**Comment by akgupta0777** [comment]
> Good day I try to use determine_banner_height but I'm having AttributeError: 'KivMob' Object has no attribute determine_banner_height

You forgot to update the kivmob package on your local machine.
