### ISSUE TITLE
AttributeError: 'MyAPP' object has no attribute 'ads'

### ISSUE THREAD

**Issue by cagricuhadaroglucc** [MichaelStott/KivMob#62]
class MyAPP(App):   
    
    def build(self):
        
        self.ads = KivMob(TestIds.APP)
        self.ads.destroy_banner()
        self.ads.new_banner(TestIds.BANNER, top_pos=True)
        self.ads.request_banner()
        self.ads.show_banner()
        return navigationdrawer   
    
    def close_ad(self):        
        self.ads.destroy_banner()

 File "/home/acer/elek/main.py", line 83, in load_module_GUI
    MyAPP().close_ad()
  File "/home/acer/elek/main.py", line 46, in close_ad
    self.ads.destroy_banner()
AttributeError: 'MyAPP' object has no attribute 'ads'

Why i get no attribute error

**Comment by cagricuhadaroglucc** [comment]
self.ads.destroy_banner() only works in def build,

**Comment by cagricuhadaroglucc** [comment]
from kivmob import KivMob, TestIds

from kivy.app import App
from kivy.uix.label import Label

class BannerTest(App):
    """ Displays a banner ad at top of the screen.
    """
    show_banner = False
    def build(self):
        self.ads = KivMob(TestIds.APP)
        self.ads.new_banner(TestIds.BANNER, top_pos=True)
        self.ads.request_banner()
        self.ads.show_banner()
        
        return Label(text='Banner Ad Demo')
    def toggle_banner(self):
        self.show_banner = not self.show_banner
        if self.show_banner:
            self.ads.show_banner()
        else:
            self.ads.hide_banner()
                
BannerTest().toggle_banner()
    

if __name__ == "__main__":
    BannerTest().run()


what is wrong with this easy code same error

"self.ads.show_banner()
AttributeError: 'BannerTest' object has no attribute 'ads'"

same errors can u help for them

**Comment by MichaelStott** [comment]
@cagricuhadaroglucc Reformatted your code for readability. 
```python
from kivmob import KivMob, TestIds

from kivy.app import App
from kivy.uix.label import Label

class BannerTest(App):
    """ Displays a banner ad at top of the screen.
    """
    show_banner = False
    
    def build(self):
        self.ads = KivMob(TestIds.APP)
        self.ads.new_banner(TestIds.BANNER, top_pos=True)
        self.ads.request_banner()
        self.ads.show_banner()
        self.toggle_banner()
        return Label(text='Banner Ad Demo')
    
    def toggle_banner(self):
        self.show_banner = not self.show_banner
        if self.show_banner:
            self.ads.show_banner()
        else:
            self.ads.hide_banner()

# This will fail
BannerTest().toggle_banner()

if __name__ == "__main__":
    BannerTest().run()
```
The problem is that `ads` hasn't been instantiated yet when you call BannerTest().toggle_banner(). It is instantiated in the `build` method of your BannerTest app, and that won't be implicitly called until you call `run` on your app class. Check Kivy's documentation for more information regarding this.

**Comment by cagricuhadaroglucc** [comment]
When i bind "BannerTest().toggle_banner()" to button and after "run" , when i call it it gives the same error. Yes, it is so how can call "hide_banner" by any widget. Pls, give me example for that..

**Comment by cagricuhadaroglucc** [comment]
There was no exact answer but the answer was this. it workss..

from kivmob import KivMob, TestIds

from kivy.app import App
from kivy.uix.label import Label

class BannerTest(App):
    """ Displays a banner ad at top of the screen.
    """
    show_banner = False
    self.ads = KivMob(TestIds.APP) #this is the answer
    def build(self):
        
        self.ads.new_banner(TestIds.BANNER, top_pos=True)
        self.ads.request_banner()
        self.ads.show_banner()
        self.toggle_banner()
        return Label(text='Banner Ad Demo')
    
    def toggle_banner(self):
        self.show_banner = not self.show_banner
        if self.show_banner:
            self.ads.show_banner()
        else:
            self.ads.hide_banner()

# This will fail
BannerTest().toggle_banner()

if __name__ == "__main__":
    BannerTest().run()

**Comment by cagricuhadaroglucc** [comment]
There was no exact answer but the answer was this. it workss..

from kivmob import KivMob, TestIds

from kivy.app import App
from kivy.uix.label import Label

class BannerTest(App):
""" Displays a banner ad at top of the screen.
"""
show_banner = False
self.ads = KivMob(TestIds.APP) #this is the answer
def build(self):

    self.ads.new_banner(TestIds.BANNER, top_pos=True)
    self.ads.request_banner()
    self.ads.show_banner()
    self.toggle_banner()
    return Label(text='Banner Ad Demo')

def toggle_banner(self):
    self.show_banner = not self.show_banner
    if self.show_banner:
        self.ads.show_banner()
    else:
        self.ads.hide_banner()

This will work now

BannerTest().toggle_banner()

if name == "main":
BannerTest().run()
