### ISSUE TITLE
Different ad units for different banner ads

### ISSUE THREAD

**Issue by akgupta0777** [MichaelStott/KivMob#67]
This is a question

Do I have to create multiple banner ads units for different screens in my app.

I tested only one sample banner ad and called it in build function
And banner ad shown and appears for all screens.

If I create multiple banner ad units do i paid more from Google.

Please Tell me as soon as possible.

Thanking you for your awesome work in the kivmob repository.

**Comment by MichaelStott** [comment]
> Do I have to create multiple banner ads units for different screens in my app.
>
> I tested only one sample banner ad and called it in build function
> And banner ad shown and appears for all screens.

You're correct, ads aren't screen specific and can be invoked from anywhere in the app, so it isn't necessary to have multiple banner ads for each individual screen. It might be a nice idea to be able to associate a banner ad with a screen and to show/hide it on transition, but KivMob currently doesn't support that.

> If I create multiple banner ad units do i paid more from Google.

I don't think so. App developers are paid based on impressions. If you have a banner ad for each screen, you'll still be serving the same number of impressions overall.

> Thanking you for your awesome work in the kivmob repository.

You're welcome! :sunglasses:

**Comment by akgupta0777** [comment]
Thank You Sir for your suggestion
