### ISSUE TITLE
Loading ads again

### ISSUE THREAD

**Issue by akgupta0777** [MichaelStott/KivMob#68]
For loading interstitial ads 
do i have to call new_interstial method and request interstitial method again and again for loading interstitial ads.

What does the new_interstial method do.

I build the app with calling only request_interstitial method for loading ad whereever i need that and the ad loads too

But i am confused that it will show the same ad each time because i am not calling new_interstial method.

**Comment by MichaelStott** [comment]
You do not have to call `new_interstitial` every time, only once. `new_interstitial` creates an underlying interstitial ad object. `request_interstitial` will attempt to fetch a new ad from AdMob..
