### ISSUE TITLE
Android API-Level and NDK-version

### ISSUE THREAD

**Issue by NameKhan72** [MichaelStott/KivMob#69]
Hello,

in this support page: [developer.android](https://developer.android.com/distribute/best-practices/develop/target-sdk) it is meantioned, that apps to be published on the play-store must at least target API-Level 28.

In the kivmob documentation it is recommended to target API-Level 27.
 [KivMob doc](http://kivmob.com/tutorials.html#android-configuration)

I don't really know what to do here. Do I change it or do I leave it?

Best Regards

**Comment by akgupta0777** [comment]
Yeah That's completely fine i think, Because Android API are used to specify upto which android version they are compatible to.

For eg Android API 27 refer to Android 8 oreo
[All Google Codenames and API ](https://source.android.com/setup/start/build-numbers) 
The link above will tell you which API is used for which Android Version.

Hope this helps

**Comment by NameKhan72** [comment]
Yeah, that makes sense. 
Thanks a lot
closing this now

**Comment by GrandmasterSivaram** [comment]
No please make it 28 API ,because I got an error in playstore that the api must be 28

**Comment by NameKhan72** [comment]
I want to add that NDK-Version 17b doesn't work. Buildozer spits out an error. I use v.19.

**Comment by NameKhan72** [comment]
Quick Summary:

-NDK version 17b doesn't work: commenting out the line does (I think the default is version 19)

-API-Level 28 is required and works 

-Python 3 works instead of Python2 

-SDK-Version works for now

Tested with the [rewarded video example](http://kivmob.com/tutorials.html#rewarded-video).

**Comment by akgupta0777** [comment]
The NDK version 19b(or higher) are supported.

The Ndk 17b or 17c are no longer supported and buildozer can't clone the ndk.

So use ndk version 19b

**Comment by MichaelStott** [comment]
@NameKhan72 Are you still encountering issues here?

**Comment by NameKhan72** [comment]
@MichaelStott No, everything works fine with these settings:

Quick Summary:

-NDK version 17b doesn't work: commenting out the line does (I think the default is version 19)

-API-Level 28 is required and works

-Python 3 works instead of Python 2

-SDK-Version works for now

Tested with the rewarded video example.

Thanks for asking
