### ISSUE TITLE
Reference Error when adding interstitial and banner ad

### ISSUE THREAD

**Issue by GrandmasterSivaram** [MichaelStott/KivMob#70]
I am implementing banner and interstitial ads with kivmob. When I only add banner ads, and not interstitial ads, the programm is working. When I only add interstitial ads and no banner ads, the programm is working too.I can see the ads on my phone. But when I add both of them I am getting the error in logcat: Reference Error- weakly referenced object no longer exits. Another thing to mention is that it worked yesterday perfectly, but somehow today it is not working and I did not change any code. It would be great if anybody could help me
This is my code
![admob error](https://user-images.githubusercontent.com/46606237/78906146-46792080-7a7f-11ea-966e-9dfc8b70fcf9.PNG)

This is the error
![admob error](https://user-images.githubusercontent.com/46606237/78992851-92d66600-7b3c-11ea-80cb-ccd79a3ac159.PNG)

**Comment by GrandmasterSivaram** [comment]
Edit: I don't know why but for one ad the error is coming too. Now I can see the banner ad but the app immediately closes. Without the ad, the app is working

**Comment by akgupta0777** [comment]
This is because you created two same ad instances in your code.You are allowed to create One Ad Instance.
If you want to create multiple ad instance then give them some other name.

Change these lines in the last 5 lines in on_start() method
  
```
self.ads = KivMob("ca-app-pub-XXXXXXXXXXXXXXXXXXXX")  
self.ads.new_banner("ca-app-pub-xxxxxxxxxxxxxxxxxxxx")
self.ads.add_test_device("ca-app-pub-XXXXXXXXXXXXXXXX")
self.ads.request_banner()
self.ads.show_banner()
```
with these line
```
self.another_ad = KivMob("ca-app-pub-XXXXXXXXXXXXXXXXXXX")
self.another_ad.new_banner("ca-app-pub-xxxxxxxxxxxxxxxxxxxx")
self.another_ad.add_test_device("ca-app-pub-XXXXXXXXXXXXXXXX")
self.another_ad.request_banner()
self.another_ad.show_banner()
```
```
That will fix this error

**Comment by GrandmasterSivaram** [comment]
But I want both interstitial and banner ad. Not 2 banner ads

**Comment by GrandmasterSivaram** [comment]
No succes, I also reinstalled everythink but it is not working
Here is my full code, maybe I did something wrong in the py file
`class MainApp(App):

    def build(self):
        return GUI

    def change_screen(self,screen_name):
        # get the screen manager from the kv file
        screen_manager = self.root.ids['screen_manager']
        screen_manager.current = screen_name
        # screen_manager = self.root.ids

    def on_start(self):
        self.ads = KivMob("ca-app-pub-***************")
        self.ads.new_interstitial("ca-app-pub-*************")
        self.ads.add_test_device("***********")
        self.ads.request_interstitial()
        self.ads.new_banner("ca-app-pub-************",top_pos=False)
        self.ads.request_banner()
        self.ads.show_banner()
        from kivy.base import EventLoop
        EventLoop.window.bind(on_keyboard = self.hook_keyboard)
      
    def hook_keyboard(self,window,key,*largs):
        if key == 27:
            # write whatever u want
            self.change_screen("home_screen")
            return True
    def on_resume(self):
        self.ads.request_interstitial()




MainApp().run()
`
Could anybody please check and see

**Comment by akgupta0777** [comment]
Writing all the ads related code under build method may fix the errors
As the objects and ad requests will be sent as soon the app starts.

**Comment by akgupta0777** [comment]
Because build method is called only once and is used for initializing the app.

**Comment by MichaelStott** [comment]
@GrandmasterSivaram It's difficult to say. You are trying to present the ad right after calling request_banner, so it's possible that it hasn't loaded yet. Can you share your logcat output?

**Comment by GrandmasterSivaram** [comment]
Hi michael could you show me a sample py file how I could write it. Because I just copied from the docs and it worked for one day. . Ya sure I will show the logcat output. Thank u for the help

**Comment by GrandmasterSivaram** [comment]
this is my logcat output. As you can see at the end i have the error reference error
[my_log.txt](https://github.com/MichaelStott/KivMob/files/4464490/my_log.txt)

**Comment by akgupta0777** [comment]
Please add buildozer.spec too for resolving this issue

**Comment by GrandmasterSivaram** [comment]
# (str) Title of your application
title = UQUiz

# (str) Package name
package.name = UQUiz

# (str) Package domain (needed for android/ios packaging)
package.domain = org.sivaram

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,android,jnius,kivmob

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
presplash.filename = %(source.dir)s/logo_flash.png

# (str) Icon of the application
icon.filename = %(source.dir)s/logo.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET,ACCESS_NETWORK_STATE

# (int) Target Android API, should be as high as possible.
android.api = 28

# (int) Minimum API your APK will support.
android.minapi = 21

# (int) Android SDK version to use
android.sdk = 24

# (str) Android NDK version to use
android.ndk = 19b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
android.gradle_dependencies ='com.google.firebase:firebase-ads:10.2.0'

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
android.meta_data =com.google.android.gms.ads.APPLICATION_ID=ca-app-pub-*******

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

**Comment by akgupta0777** [comment]
I have gone through the logs and buildozer and found a Warning in the log which says

Base provider unknown<android> 
I am guessing that you are running your app on a android phone that is below android version 5.0
Is that correct??

**Comment by GrandmasterSivaram** [comment]
Hi no my android version is 7.0

**Comment by akgupta0777** [comment]
Recheck requirements check your whole code if you imported any other module and didn't reference it in buildozer.spec requirements line

And then do a clean build by this command
buildozer android clean

**Comment by GrandmasterSivaram** [comment]
after clean building half way I get the error : Error while finding module specification for cython.Build.Cythonize. And I already have cython. I get the erro beacause of jnius

**Comment by akgupta0777** [comment]
Update all dependencies one more time by 
sudo apt-update
Then rebuild app by buildozer android debug

Moreover this is not a kivmob issue By the way this is a python issue.

**Comment by MichaelStott** [comment]
@GrandmasterSivaram Just checking, are you still having issues here?

**Comment by GrandmasterSivaram** [comment]
unfortunately yes

**Comment by GrandmasterSivaram** [comment]
Closing it now. Because I think it was issue of my code. My another app is working with banner ads
