### ISSUE TITLE
Documentation not containing information about included .aar files.

### ISSUE THREAD

**Issue by NameKhan72** [MichaelStott/KivMob#71]
Hello,

I just compiled my app with KivMob support. Everything works fine after some troubleshooting.
The issue was:

I was using the android-support-compat-28.0.0.aar to request runtime permissions. I included it in the buildozer.spec file. That resulted in some gigantic error message.

The core error message was: "transformDexArchiveWithExternalLibsDexMergerForDebug"

After excluding the aar from the buildozer.spec everything worked fine. Apparently KivMob already comes with the support-compat file.

This isn't really an issue on KivMobs side (It's quite convenient actually). This post is just to save someone else the headache.

TL-DR: android-support-compat-28.0.0.aar already included with KivMob

**Comment by MichaelStott** [comment]
Thanks for letting everyone know. I usually try to avoid manually adding aar files and let gradle handle installing android dependencies whenever possible, so I haven't encountered this before. I've been thinking of adding a build section to the docs that would cover any caveats/pitfalls such as these.
