### ISSUE TITLE
How to implement banners on different screens?

### ISSUE THREAD

**Issue by Felipe738743872** [MichaelStott/KivMob#72]
Hello! I’m trying to implement different Banners on different screens in my app, but I don’t I know if I'm right ...

I can create just one function in the App class, and call it when do I enter the screen?

### main.py

```
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen
from kivy.lang.builder import Builder
from kivmob import KivMob


KV_LANG = '''
#:import MDFillRoundFlatButton kivymd.uix.button.MDFillRoundFlatButton

ScreenManager
    Screen
        name: 'menu'
        MDFillRoundFlatButton
            text: 'Open screen1'
            size_hint: 0.5, 0.1
            pos_hint: {'center_x':.500, 'center_y':.600}
            on_release: app.root.current = 'screen1'
            
        MDFillRoundFlatButton
            text: 'Open screen2'
            size_hint: 0.5, 0.1
            pos_hint: {'center_x':.500, 'center_y':.400}
            on_release: app.root.current = 'screen2'
            

    MyScreen1
        name: 'screen1'
    
    MyScreen2
        name: 'screen2'
'''


class MyScreen1(Screen):
    def on_pre_enter(self):
        MDApp.get_running_app().__SHOW_BANNER__()

class MyScreen2(Screen):
    def on_pre_enter(self):
        MDApp.get_running_app().__SHOW_BANNER__()


class Kivmob(MDApp):
    def build(self):
        APP_ID = "ca-app-pub-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        self.ids = KivMob(APP_ID)
        BANNER_ID = "ca-app-pub-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        self.ids.new_banner(BANNER_ID, top_pos=False)
        self.ids.request_banner()
        return Builder.load_string(KV_LANG)

    def __SHOW_BANNER__(self):
        self.ids.show_banner()


Kivmob().run()
```

Does this create a unique banner for each screen?

**Comment by akgupta0777** [comment]
Yeah You are doing it right.This code works and ad is shown on entering the screen.
But do you know if you show a banner ad in one of a screens , The Ad automatically placed in all the other screens.
So For best practice call it once in any screen or part of program.

I Prefer to create, Request and show the banner ad in build function so that ads loaded on startup.

**Comment by MichaelStott** [comment]
@Felipe738743872 Updated the example to remove the ad ids.  The above code won't create an ad for each screen. You instantiated the banner ad in the build function of the Kivy app when calling `new_banner` and the screens are attempting to show that particular ad, provided that it has loaded successfully. I think the way you have the logic structured here is fine.
