### ISSUE TITLE
KivMob Buildozer compilation ERROR: No matching distribution found for hostpython2 (from -r requirements.txt (line 2))

### ISSUE THREAD

**Issue by shoumikdas** [MichaelStott/KivMob#77]
I am new to Kivy and trying to compile a simple app (sample KivMob code) into an Android apk using Buildozer on Ubuntu Linux 18.04. However, I am stuck at the following error:

**ERROR: Could not find a version that satisfies the requirement hostpython2 (from -r requirements.txt (line 2)) (from versions: none)**

**ERROR: No matching distribution found for hostpython2 (from -r requirements.txt (line 2))**

As per the KivMob documentation, the requirements are specified as follows:

**requirements = python3,kivy,android,kivmob,hostpython2,jnius**

I searched on Google and realized that hostpython2 is deprecated. Does KivMob really need hostpython2? What should be my correct requirement list?

**Comment by akgupta0777** [comment]
No it doesn't need host python 2. Simply remove it from the requirements and rebuild 
With buildizer android debug

**Comment by shoumikdas** [comment]
Thank you. I just used python3 and it worked. I was referring to the documentation on the KivMob site and it used hostpython2. Hence, the confusion. Thanks for your help.
