### ISSUE TITLE
App published on playstore

### ISSUE THREAD

**Issue by GrandmasterSivaram** [MichaelStott/KivMob#79]
Hi Michael, thank u for kivmob. This is not an issue. I just wanted to say that my app is published on google playstore with admob ads. It is a weather app.
App: Easy Weather - Live Weather with 5 day forecast
Play Store Link: https://play.google.com/store/apps/details?id=org.sivaram.easyweather
Author: Sivaram Yadav Nalliboyana
Thank u very much

**Comment by MichaelStott** [comment]
Thanks, your app is now in the README.
