### ISSUE TITLE
Google Admob account with many requests but banner not showing

### ISSUE THREAD

**Issue by mateoaita** [MichaelStott/KivMob#81]
Hello! I've built a kivy app and everything went fine. I have like 150 request at my Admob account but the banner is not there. I don't know if there is a number of requests you need to reach so that google places a banner in your app. The app is available at aptoide (android appstore different to PlayStore), could the problem be related to that? Thanks for the time!

**Comment by akgupta0777** [comment]
Share the link for the app on aptoide

**Comment by mateoaita** [comment]
https://www.aptoide.com (you have to open the following link with aptoide)

https://tact-it.es.aptoide.com/?store_name=camost&app_id=52089798

Sorry for answering 3 days later, I was bussy with faculty stuff!

**Comment by MichaelStott** [comment]
Closing for now. Feel free to reopen if there is still an issue.
