### ISSUE TITLE
Rewarded video documentation/example required

### ISSUE THREAD

**Issue by lokapal** [MichaelStott/KivMob#84]
Hello!
    Could you, please, supply documentation/example for the rewarded video. I've seen demo application, and have a few questions concerning it:
How is called the method def on_rewarded_video_a_completed(self)? I've tried to do something like your demo, but in my program this method is never called. 
    Yet another question: does these callbacks are working under Windows/Linux or all kivmob functionality is blocked?

**Comment by akgupta0777** [comment]
@lokapal the method on_rewarded_ad_completed() will be called when user watches the ad completely.
These rewarded functions only trigger while playing ad on android devices.

KivMob rewarded video ads don't work in windows/linux or PC because they need some android SDK and stuff like that.

So for testing your rewarded video ads callback functions package your code in an apk file and then run it on either Mobile or Android Emulator.

For further explanation how they got implemented 

See code in demos section  or read documentation available on KivMob.com

**Comment by lokapal** [comment]
As a matter of fact demo source is not documented almost, and documentation doesn't tell anything about scope of this functions. It works automatically if all system is binded to the main app only (not to layout).

**Comment by lokapal** [comment]
As a matter of fact demo source is not documented almost, and documentation doesn't tell anything about scope of this functions. It works automatically if all system is binded to the main app only (not to layout).

**Comment by lokapal** [comment]
As a matter of fact demo source is not documented almost, and documentation doesn't tell anything about scope of this functions. It works automatically if all system is binded to the main app only (not to layout).

**Comment by lokapal** [comment]
As a matter of fact demo source is not documented almost, and documentation doesn't tell anything about scope of this functions. It works automatically if all system is binded to the main app only (not to layout).

**Comment by lokapal** [comment]
As a matter of fact demo source is not documented almost, and documentation doesn't tell anything about scope of this functions. It works automatically if all system is binded to the main app only (not to layout).

**Comment by lokapal** [comment]
As a matter of fact demo source is not documented almost, and documentation doesn't tell anything about scope of this functions. It works automatically if all system is binded to the main app only (not to layout).

**Comment by lokapal** [comment]
As a matter of fact demo source is not documented almost, and documentation doesn't tell anything about scope of this functions. It works automatically if all system is binded to the main app only (not to layout).
