### ISSUE TITLE
La Carta

### ISSUE THREAD

**Issue by RoberWare** [MichaelStott/KivMob#86]
Hey!, I use KivMob in my Android app and it's fully functional!.
I uploaded it to Google Play!. Thank you for your work.
The app is in Spanish but in the next version I will translate it to English and French.
 - Name of the app: La Carta (The Menu)
 - Description: 
    The first time you go to the restaurant, you must scan the QR code on the menu. But the next time it will be enough to open the app and it will directly show you the menu of the closest restaurant that you have stored.
You can also see all the other letters, share them or delete them from your history.
 - Link: 
        [https://play.google.com/store/apps/details?id=com.blogspot.roberware.lacarta](url)

**Comment by MichaelStott** [comment]
Congratulations on releasing your app! It's now showcased in the README.
