### ISSUE TITLE
Solicitação de anuncios

### ISSUE THREAD

**Issue by da794** [MichaelStott/KivMob#93]
Eu usei o kivmob com o anúncio de teste e funcionou perfeitamente, mas, quando coloquei o ID do meu app e do bloco de anuncios não aparece anuncios nenhum, aí eu suspeitei que seja porque não tem nenhuma solicitação de anuncios da rede admob. Alguém sabe porque não recebo nenhum pedido de anuncios?

**Comment by akgupta0777** [comment]
Para testar seus próprios anúncios, você precisa de um ID de dispositivo de teste exclusivo para que o Google possa identificar que você não está enviando spam.
Use a id do dispositivo e adicione seu dispositivo no código pela função add_device (YOUR_DEVICE_ID).
