### ISSUE TITLE
Mais de um bloco de anúncio

### ISSUE THREAD

**Issue by da794** [MichaelStott/KivMob#94]
É possível por mais de um bloco de anuncios no meu app, tipo um banner e um intersticial com kivmob?

**Comment by akgupta0777** [comment]
Sim, é possível que você precise criar mais blocos de anúncios a partir de sua conta AdMob e então usar o UNIT ID onde quiser em seu código.

**Comment by MichaelStott** [comment]
From what I can gather from Google Translate, this has been answered.
